import { Activity, Microscope, HeartPulse, Globe, Users, ShieldCheck, Clock, Stethoscope, Bed, Zap, AlertTriangle, FlaskConical, Brain } from "lucide-react";
import type { HospitalSubData } from "./HospitalSubPage";

export const hospitalSubData: Record<string, HospitalSubData> = {

  /* ─────────────────── OPD SERVICES ─────────────────── */
  opd: {
    name: "OPD Services",
    accent: "amber",
    heroImage: "/hospital_opd_hd.png",
    introImages: [],
    splitImage: "/hospital_interior_hd.png",
    faqImage: "/hospital_opd_hd.png",
    heroTitleLine1: "Walk in.",
    heroTitleLine2: "Walk out healthier.",
    ctaTagline: "Expert consultations, all under one roof.",
    introBadge: "Outpatient Department\nSee a doctor, not a queue.",
    introHeadline: "Modern OPD Care — for People and Practitioners.",
    introCards: [
      { value: "20+", unit: "specs", title: "Consultation Rooms", desc: "Multi-speciality rooms for general medicine, surgery, paediatrics, ortho & more.", img: "/hospital_opd_hd.png" },
      { value: "500+", unit: "daily", title: "Patient Footfall", desc: "Trusted daily by 500+ patients from Gaya, Bodhgaya and surrounding districts.", img: "/hospital_interior_hd.png" },
      { value: "Smart", unit: "queue", title: "Token System", desc: "Digital token & SMS alerts — minimal waiting, maximum efficiency.", img: "/hospital_hero_hd.png" },
      { value: "Online", unit: "book", title: "Easy Booking", desc: "Book your OPD slot online or via phone — confirmation in seconds.", img: "/hospital_icu_hd.png" },
    ],
    bigStatsHeading: "Anyone. Anytime.",
    bigStatsSubheading: "20+ specialities, 500+ daily patients.",
    features: [
      { icon: Clock, title: "No Long Wait", desc: "Smart token system, online slot booking — get seen quickly." },
      { icon: Stethoscope, title: "Expert Consultations", desc: "Specialist doctors across 20+ disciplines available daily." },
      { icon: Activity, title: "Same-Day Diagnostics", desc: "OPD-linked lab and imaging — get reports the same day." },
      { icon: Globe, title: "Multilingual Support", desc: "Hindi, English & local language support for every patient." },
    ],
    servicesBadge: "What We Offer",
    servicesHeading: "Comprehensive outpatient consultation services.",
    services: [
      { num: "01", title: "General Medicine OPD", desc: "Daily consultations for fever, infections, chronic disease management." },
      { num: "02", title: "Specialist Clinics", desc: "Cardiology, neurology, endocrinology, gastroenterology specialty clinics." },
      { num: "03", title: "Surgical OPD", desc: "Pre-operative consultations, follow-ups, and minor procedures." },
      { num: "04", title: "Paediatric OPD", desc: "Dedicated child-friendly consultation rooms with play area." },
      { num: "05", title: "Women's Health OPD", desc: "Obstetrics, gynaecology, antenatal care and family planning." },
      { num: "06", title: "Health Check-ups", desc: "Preventive health packages — basic, comprehensive, and executive." },
    ],
    splitHeading: "One stop.\nOne visit.",
    splitText: "From consultation to lab tests, imaging, and pharmacy — every OPD visit at BHRI is designed to be complete and stress-free. Walk in for a consultation, walk out with all your reports and prescriptions in hand.",
    splitBadgeTitle: "OPD Reception",
    splitBadgeSub: "Open Mon-Sat, 9 AM – 4 PM",
    facilities: [
      "20+ Consultation Rooms",
      "Smart Digital Token System",
      "Online & Phone Booking",
      "On-site Diagnostic Lab",
      "Imaging Centre",
      "Pharmacy Counter",
      "Wheelchair Access",
      "Air-Conditioned Waiting Area",
    ],
    stats: [
      { value: "500+", label: "Daily Visits" },
      { value: "20+", label: "Specialities" },
      { value: "<30m", label: "Avg Wait Time" },
      { value: "Mon–Sat", label: "9 AM – 4 PM" },
    ],
    faqs: [
      { q: "What are the OPD timings?", a: "Our OPD operates Monday to Saturday from 9:00 AM to 4:00 PM. Sundays are reserved for emergency consultations only. Specialist clinics may have specific days — please check the schedule before visiting." },
      { q: "How can I book an OPD appointment?", a: "You can book an OPD appointment online via our website, by calling our 24×7 helpline at +91 8603048174 / 9060646592, or by walking into our reception. Online booking lets you choose your doctor and time slot." },
      { q: "Do I need a referral to see a specialist?", a: "No. You can directly book a specialist OPD appointment without any referral. However, having previous medical records helps the specialist provide better care." },
      { q: "What documents should I bring?", a: "Bring any past medical records, prescriptions, lab reports, and a valid ID proof. If you are using insurance, also bring your insurance card or policy details." },
      { q: "Are OPD consultations available for children?", a: "Yes. We have a dedicated Paediatric OPD with child-friendly consultation rooms, vaccination clinic, and growth monitoring. Daily timings are 9 AM – 1 PM with evening slots on selected days." },
      { q: "Is OPD covered by insurance?", a: "OPD coverage depends on your insurance plan. Some comprehensive plans cover OPD consultations and diagnostics. Check with our insurance desk for details on your specific policy." },
    ],
    ctaHeadingLine1: "Healthcare,",
    ctaHeadingLine2: "without the wait.",
    ctaText: "Book your OPD appointment with our specialists today. Walk-ins are welcome, but online booking ensures you get a guaranteed slot with minimal wait time.",
  },

  /* ─────────────────── IN-WARDS SERVICES ─────────────────── */
  "in-wards": {
    name: "In-Wards Services",
    accent: "amber",
    heroImage: "/hospital_icu_hd.png",
    introImages: [],
    splitImage: "/hospital_interior_hd.png",
    faqImage: "/hospital_icu_hd.png",
    heroTitleLine1: "Comfort.",
    heroTitleLine2: "Care. Recovery.",
    ctaTagline: "Modern wards designed for healing.",
    introBadge: "Inpatient Department\nWhere recovery feels like home.",
    introHeadline: "Spacious Wards & Critical Care Units, designed for comfort.",
    introCards: [
      { value: "300", unit: "beds", title: "Bed Capacity", desc: "General, semi-private, private rooms and dedicated suites for every need.", img: "/hospital_icu_hd.png" },
      { value: "ICU", unit: "24×7", title: "Critical Care", desc: "Dedicated ICU, NICU and PICU staffed by intensivists round-the-clock.", img: "/hospital_interior_hd.png" },
      { value: "1:1", unit: "care", title: "Nursing Ratio", desc: "Trained nursing staff with dedicated patient assignments for personalised care.", img: "/hospital_hero_hd.png" },
      { value: "Private", unit: "AC", title: "Premium Suites", desc: "Air-conditioned private rooms with attendant facility, TV, and Wi-Fi.", img: "/hospital_ot_hd.png" },
    ],
    bigStatsHeading: "Healing. Holistic.",
    bigStatsSubheading: "300+ beds, 24×7 critical care.",
    features: [
      { icon: Bed, title: "Comfortable Wards", desc: "Spacious clean wards with private and shared room options to suit all budgets." },
      { icon: HeartPulse, title: "Constant Monitoring", desc: "Real-time vital monitoring in critical care areas, around-the-clock nursing." },
      { icon: Users, title: "Family Support", desc: "Attendant facility, visiting hours, and counsellor support for families." },
      { icon: ShieldCheck, title: "Strict Hygiene", desc: "Hospital-grade sanitisation, infection-control protocols, single-use supplies." },
    ],
    servicesBadge: "Inpatient Care",
    servicesHeading: "Complete inpatient services for every need.",
    services: [
      { num: "01", title: "General Wards", desc: "Affordable, well-maintained wards for patients with ongoing treatment." },
      { num: "02", title: "Private Rooms", desc: "Air-conditioned private rooms with attendant bed, washroom, and TV." },
      { num: "03", title: "ICU / HDU", desc: "Multi-disciplinary ICU for cardiac, respiratory, and critical care patients." },
      { num: "04", title: "NICU & PICU", desc: "Specialised neonatal and paediatric ICUs with ventilatory support." },
      { num: "05", title: "Maternity Ward", desc: "Postnatal wards with mother-baby rooming-in and lactation support." },
      { num: "06", title: "Day Care Services", desc: "Short-stay wards for chemotherapy, dialysis, and day procedures." },
    ],
    splitHeading: "Healing,\nin every room.",
    splitText: "Every patient at BHRI receives more than just treatment — they receive an environment built for healing. Clean, comfortable wards, dedicated nursing care, and modern medical equipment ensure that every stay is focused on recovery and dignity.",
    splitBadgeTitle: "Critical Care Unit",
    splitBadgeSub: "ICU, NICU & PICU available",
    facilities: [
      "Air-conditioned Private Rooms",
      "ICU / HDU / NICU / PICU",
      "Maternity Ward",
      "Attendant Facility",
      "In-room TV & Wi-Fi",
      "Patient Call System",
      "Trained Nursing 24×7",
      "Dietitian Counsel Service",
    ],
    stats: [
      { value: "300+", label: "Operational Beds" },
      { value: "30+", label: "ICU Beds" },
      { value: "20", label: "NICU Beds" },
      { value: "24×7", label: "Nursing Care" },
    ],
    faqs: [
      { q: "What types of rooms are available?", a: "We offer general wards, semi-private rooms, private rooms, and deluxe suites. Each option includes a bed, basic furniture, attached or shared washroom, and 24×7 nursing care. Private rooms include AC, TV, Wi-Fi, and an attendant bed." },
      { q: "Can a family member stay with the patient?", a: "Yes. Private rooms include an attendant bed. Even in general wards, one family attendant is allowed during specified hours. ICU patients have controlled visiting hours for safety." },
      { q: "How is critical care different at BHRI?", a: "Our ICU, NICU and PICU are equipped with modern ventilators, monitors, and specialised staff. Intensivists and trained ICU nurses provide round-the-clock care with dedicated 1:2 nurse-patient ratio." },
      { q: "What is the cost for inpatient services?", a: "Costs vary by room type, treatment, and length of stay. We offer transparent billing, insurance cashless tie-ups, and counselling for treatment estimates. Ask our admissions desk for a detailed package." },
      { q: "Do you offer cashless insurance for admissions?", a: "Yes. We have cashless tie-ups with major TPAs and government schemes (Ayushman Bharat, CGHS, ECHS). Pre-authorisation is required — our insurance desk handles the entire process." },
      { q: "Are visitors allowed in the wards?", a: "Yes, with restrictions. General wards: 4–7 PM daily. ICU/NICU: 11 AM–12 noon and 5–6 PM, one visitor at a time. Children below 12 not allowed in critical care areas." },
    ],
    ctaHeadingLine1: "Comfort, dignity,",
    ctaHeadingLine2: "every step of healing.",
    ctaText: "Need admission or have a question about our wards? Speak to our admissions team to understand your options, room availability, and insurance coverage.",
  },

  /* ─────────────────── DIAGNOSTIC SERVICES ─────────────────── */
  diagnostics: {
    name: "Diagnostic Services",
    accent: "teal",
    heroImage: "/hospital_interior_hd.png",
    introImages: [],
    splitImage: "/hospital_icu_hd.png",
    faqImage: "/hospital_interior_hd.png",
    heroTitleLine1: "Precision.",
    heroTitleLine2: "Accuracy. Speed.",
    ctaTagline: "Modern diagnostics, fast results.",
    introBadge: "Diagnostic Services\nKnow before you treat.",
    introHeadline: "Lab, Imaging & Pathology — under one roof.",
    introCards: [
      { value: "12+", unit: "labs", title: "Diagnostic Labs", desc: "Pathology, biochemistry, haematology, microbiology — all NABL-grade.", img: "/hospital_interior_hd.png" },
      { value: "MRI/CT", unit: "imaging", title: "Imaging Suite", desc: "MRI, CT, ultrasound, X-ray, mammography — modern equipment, expert reporting.", img: "/hospital_icu_hd.png" },
      { value: "<24h", unit: "report", title: "Fast Reports", desc: "Most lab reports in 4–24 hrs. Imaging reports same-day with online access.", img: "/hospital_hero_hd.png" },
      { value: "100%", unit: "digital", title: "Digital Records", desc: "Reports delivered via email & app. Lifelong digital health record.", img: "/hospital_ot_hd.png" },
    ],
    bigStatsHeading: "Smart. Reliable.",
    bigStatsSubheading: "Diagnosis backed by precision technology.",
    features: [
      { icon: Microscope, title: "Modern Equipment", desc: "Latest analysers, scanners, and imaging machines for accurate results." },
      { icon: FlaskConical, title: "NABL-Grade Lab", desc: "Quality-certified pathology and clinical laboratory services." },
      { icon: Brain, title: "Expert Radiologists", desc: "Imaging reported by senior radiologists with sub-specialty expertise." },
      { icon: Clock, title: "Fast Turnaround", desc: "Most reports in 4–24 hours, with emergency reports available within an hour." },
    ],
    servicesBadge: "What We Test",
    servicesHeading: "Comprehensive diagnostic capabilities.",
    services: [
      { num: "01", title: "Pathology Lab", desc: "Histopathology, cytology, biopsy reporting with expert pathologist review." },
      { num: "02", title: "Biochemistry", desc: "Liver function, kidney function, lipid profile, diabetes, hormone tests." },
      { num: "03", title: "Haematology", desc: "Complete blood count, coagulation, blood typing, peripheral smear." },
      { num: "04", title: "Microbiology", desc: "Culture & sensitivity, infectious disease testing, antibiotic profiling." },
      { num: "05", title: "Imaging — MRI/CT/X-Ray", desc: "Cross-sectional imaging, mammography, fluoroscopy and ultrasonography." },
      { num: "06", title: "Cardiac Diagnostics", desc: "ECG, echocardiography, stress test, holter monitoring." },
    ],
    splitHeading: "Accurate.\nFast. Trusted.",
    splitText: "Our diagnostics team combines modern technology with experienced specialists to deliver precise, timely results. From routine blood tests to advanced imaging, every report is reviewed by an expert before being released — because accurate diagnosis is the foundation of effective treatment.",
    splitBadgeTitle: "Imaging Centre",
    splitBadgeSub: "MRI, CT, USG, X-Ray, Mammo",
    facilities: [
      "NABL Pathology Lab",
      "1.5T MRI Scanner",
      "Multi-slice CT Scanner",
      "Digital X-Ray & Fluoroscopy",
      "4D Ultrasound",
      "Digital Mammography",
      "Cardiac Diagnostics Lab",
      "Sample Collection at Home",
    ],
    stats: [
      { value: "12+", label: "Diagnostic Labs" },
      { value: "1000+", label: "Tests Available" },
      { value: "<24h", label: "Report Time" },
      { value: "24×7", label: "Emergency Lab" },
    ],
    faqs: [
      { q: "What diagnostic services are available at BHRI?", a: "We offer comprehensive diagnostics including pathology (histopath, cytology), clinical biochemistry, haematology, microbiology, immunology, cardiac diagnostics (ECG, echo), and full imaging (X-ray, USG, CT, MRI, mammography)." },
      { q: "How quickly will I get my reports?", a: "Most routine lab reports are ready within 4–24 hours. Specialised tests like culture-sensitivity may take 48–72 hours. Imaging reports are typically available the same day. Emergency reports are processed within an hour." },
      { q: "Can I get my reports online?", a: "Yes. All reports are available digitally — sent via email and accessible through our patient portal/app. You can also collect a printed copy from the diagnostics counter." },
      { q: "Do I need a doctor's referral for tests?", a: "Most routine tests can be done without a referral, but for some specialised investigations (like advanced MRI sequences or invasive biopsies), a doctor's prescription is recommended for accurate clinical correlation." },
      { q: "Is home sample collection available?", a: "Yes. We provide home sample collection for blood, urine, and stool tests within Gaya city. Call our diagnostic helpline to schedule a collection at your preferred time." },
      { q: "Are the reports recognised by other hospitals?", a: "Absolutely. Our pathology and imaging reports are NABL-grade quality and are recognised by all major hospitals, insurers, and government schemes across India." },
    ],
    ctaHeadingLine1: "Trusted reports,",
    ctaHeadingLine2: "trusted treatment.",
    ctaText: "Book a diagnostic test or full health check-up package today. Our team can help guide you to the right tests and explain the results in simple terms.",
  },

  /* ─────────────────── EMERGENCY SERVICES ─────────────────── */
  emergency: {
    name: "Emergency Services",
    accent: "amber",
    heroImage: "/hospital_emergency_hd.png",
    introImages: [],
    splitImage: "/hospital_icu_hd.png",
    faqImage: "/hospital_emergency_hd.png",
    heroTitleLine1: "Always.",
    heroTitleLine2: "Awake. Ready.",
    ctaTagline: "When seconds count, we're here.",
    introBadge: "Emergency Department\nLife-saving care, day and night.",
    introHeadline: "Trauma & Emergency Care — 24×7 lifeline for Bihar.",
    introCards: [
      { value: "24×7", unit: "ER", title: "Always Open", desc: "Emergency department staffed by senior doctors, every hour, every day.", img: "/hospital_emergency_hd.png" },
      { value: "<10m", unit: "triage", title: "Fast Triage", desc: "Critical patients seen within 10 minutes. Standardised protocols.", img: "/hospital_icu_hd.png" },
      { value: "ALS", unit: "ambo", title: "Ambulance Fleet", desc: "Advanced life support ambulances with ICU-grade equipment & paramedics.", img: "/hospital_hero_hd.png" },
      { value: "Multi", unit: "trauma", title: "Trauma Centre", desc: "Comprehensive trauma care — ortho, neuro, cardiac, paediatric all on call.", img: "/hospital_ot_hd.png" },
    ],
    bigStatsHeading: "When it matters most,",
    bigStatsSubheading: "we're already on it — 24×7×365.",
    features: [
      { icon: Zap, title: "Rapid Response", desc: "Critical cases triaged within 10 minutes — our ER never sleeps." },
      { icon: AlertTriangle, title: "Trauma-Ready Team", desc: "On-call orthopaedic, neuro, cardiac, paediatric specialists round-the-clock." },
      { icon: Activity, title: "Modern Equipment", desc: "Resuscitation bays, defibrillators, ventilators, blood gas analysers ready to go." },
      { icon: ShieldCheck, title: "Insurance Cashless", desc: "Most major insurance plans accepted with cashless emergency authorisation." },
    ],
    servicesBadge: "We Handle",
    servicesHeading: "Every emergency, every minute.",
    services: [
      { num: "01", title: "Trauma & Accident", desc: "Multi-specialty trauma management — ortho, neuro, vascular, surgical." },
      { num: "02", title: "Cardiac Emergency", desc: "Heart attack, arrhythmias, cardiac arrest — door-to-needle protocols." },
      { num: "03", title: "Stroke Centre", desc: "Rapid CT, thrombolysis, neurology team available 24×7 for stroke." },
      { num: "04", title: "Paediatric Emergency", desc: "Child-specific resuscitation bays with paediatricians on call." },
      { num: "05", title: "Obstetric Emergency", desc: "Labour, eclampsia, haemorrhage — maternity team always ready." },
      { num: "06", title: "Poisoning & Snakebite", desc: "Anti-venoms, antidotes, gastric lavage and ICU back-up available." },
    ],
    splitHeading: "When seconds\ncount, we run.",
    splitText: "Every minute matters in an emergency. Our 24×7 ER team is trained to act fast — triage in minutes, resuscitation in seconds, and a dedicated path to ICU or operation theatre when needed. Call our emergency helpline at the first sign of trouble.",
    splitBadgeTitle: "ER & Trauma Centre",
    splitBadgeSub: "Active 24 × 7 × 365",
    facilities: [
      "24×7 Emergency Room",
      "Resuscitation Bays",
      "ALS Ambulance Service",
      "Trauma OT On-Call",
      "Stroke Pathway",
      "Cardiac Cath Lab On-Call",
      "Emergency Pharmacy",
      "Direct ICU Access",
    ],
    stats: [
      { value: "24×7", label: "Always Open" },
      { value: "<10m", label: "Triage Time" },
      { value: "5", label: "ALS Ambulances" },
      { value: "ICU", label: "Direct Access" },
    ],
    faqs: [
      { q: "What should I do in a medical emergency?", a: "Call our emergency helpline immediately at +91 8603048174 / 9060646592. Our ambulance team can reach you while you walk in — both work in parallel. Our ER is open 24×7 with no appointment needed for emergencies." },
      { q: "Do you have ambulance services?", a: "Yes. We operate Advanced Life Support (ALS) ambulances equipped with ventilators, defibrillators, and trained paramedics. Call our helpline — average ambulance response time within Gaya city is 10–15 minutes." },
      { q: "What kind of emergencies do you handle?", a: "All types — trauma & accidents, cardiac (heart attack, arrhythmia), stroke, paediatric emergencies, obstetric, poisoning, snakebite, severe infections. Our multi-specialty team is on call for every situation." },
      { q: "Is the emergency room open at night?", a: "Yes. Our ER operates 24 hours a day, 7 days a week, including all holidays. Senior doctors and trained nursing staff are present every hour. Specialists are on-call for immediate consultation." },
      { q: "Will insurance cover emergency treatment?", a: "Yes, most insurance policies cover emergency care. Our 24×7 insurance desk handles cashless authorisation immediately for emergencies. If pre-auth is delayed, we admit first and process the paperwork in parallel." },
      { q: "What documents do I need for emergency admission?", a: "Just bring whatever you have — emergency admission requires no prior paperwork. We need a valid ID for billing and any past medical reports if available. Insurance details can be provided after the patient is stabilised." },
    ],
    ctaHeadingLine1: "Every second",
    ctaHeadingLine2: "matters. So do we.",
    ctaText: "If you or someone you love is facing a medical emergency, don't wait. Call our 24×7 emergency helpline now — our team is ready to respond.",
  },

};

export default hospitalSubData;
