import type { DeptData } from "./DepartmentPage";

export const departments: Record<string, DeptData> = {

  anatomy: {
    name: "Anatomy",
    tagline: "Building the foundation of medicine through the science of human structure and form.",
    heroImage: "/carousel-1.png",
    splitImage: "/carousel-2.png",
    splitHeading: "Where Medicine Begins",
    splitText: "Anatomy is the cornerstone of medical education. Our department provides a rigorous, hands-on learning environment with modern cadaveric dissection facilities, 3D models, and advanced imaging-based teaching methods.",
    overview: "The Department of Anatomy at Dhamma Institute of Medical Sciences is dedicated to providing students with a thorough understanding of the human body's structural organisation. From gross anatomy and histology to embryology and neuroanatomy, our curriculum bridges fundamental science with clinical application.",
    highlights: [
      "Fully equipped dissection hall with dedicated cadaveric specimens",
      "Museum with over 500 anatomical specimens and mounted skeletons",
      "Digital anatomy lab with 3D interactive visualisation tools",
      "Regular inter-departmental clinical correlation sessions",
      "Strong emphasis on clinical anatomy in surgical and radiology contexts",
    ],
    services: [
      { title: "Gross Anatomy", desc: "Systematic study of macroscopic body structures through dissection and prosection." },
      { title: "Histology", desc: "Microscopic study of tissues and organs using modern staining and imaging techniques." },
      { title: "Embryology", desc: "Developmental anatomy from fertilisation through organogenesis and foetal stages." },
      { title: "Neuroanatomy", desc: "In-depth study of the central and peripheral nervous system structures." },
      { title: "Clinical Anatomy", desc: "Surface and radiological anatomy integrated with clinical practice and surgical skills." },
      { title: "Radiology Correlation", desc: "CT, MRI, and X-ray interpretation mapped to anatomical landmarks." },
    ],
    stats: [{ value: "500+", label: "Museum Specimens" }, { value: "20+", label: "Faculty Members" }, { value: "100%", label: "Practical Coverage" }, { value: "3D", label: "Digital Lab" }],
    facilities: ["Dissection Hall", "Anatomy Museum", "Histology Lab", "Digital Anatomy Lab", "3D Model Library", "E-learning Studio", "Research Lab", "Clinical Correlation Room"],
    faqs: [
      { q: "What is the focus of the Anatomy department?", a: "Our department focuses on all aspects of human anatomy — gross, microscopic, developmental, and neurological — integrated with clinical context for MBBS students." },
      { q: "Does the department have a cadaveric dissection facility?", a: "Yes. We have a state-of-the-art dissection hall with adequate cadaveric specimens maintained under proper preservation standards." },
      { q: "Is there a digital anatomy lab?", a: "Yes. Our 3D digital anatomy lab has interactive tools that allow students to explore the human body in immersive virtual environments." },
      { q: "How does the department correlate anatomy with clinical medicine?", a: "Through regular clinical correlation sessions, radiology integration classes, and surface anatomy practicals tied to surgery and medicine departments." },
    ],
  },

  physiology: {
    name: "Physiology",
    tagline: "Understanding life through the dynamic functions of the human body at every level.",
    heroImage: "/carousel-2.png",
    splitImage: "/carousel-3.png",
    splitHeading: "The Science of Life in Motion",
    splitText: "Our Physiology department bridges basic science and clinical medicine by teaching how the body functions in health and adapts in disease. Modern laboratory infrastructure enables hands-on learning of physiological principles.",
    overview: "The Department of Physiology at Dhamma Institute of Medical Sciences provides a strong foundation in understanding how the body's organ systems function individually and in coordination. From cellular physiology to systemic functions, students gain both theoretical knowledge and practical laboratory skills essential for clinical practice.",
    highlights: [
      "Comprehensive physiology laboratory with computerised recording systems",
      "Haematology, cardiovascular, respiratory, and neurophysiology practicals",
      "Regular integration with clinical departments for applied learning",
      "Research opportunities in cardiovascular and metabolic physiology",
      "Modern instruments for recording physiological parameters",
    ],
    services: [
      { title: "General Physiology", desc: "Cell membrane, transport mechanisms, and receptor pharmacology." },
      { title: "Cardiovascular Physiology", desc: "Cardiac cycles, haemodynamics, ECG interpretation, and vascular regulation." },
      { title: "Respiratory Physiology", desc: "Lung volumes, gas exchange, and regulatory mechanisms of breathing." },
      { title: "Renal & Endocrine", desc: "Kidney function, fluid balance, hormonal regulation, and homeostasis." },
      { title: "Neurophysiology", desc: "Nerve conduction, synaptic transmission, reflexes, and special senses." },
      { title: "Haematology Lab", desc: "Blood cell counts, bleeding time, clotting time, and haemoglobin estimation." },
    ],
    stats: [{ value: "30+", label: "Practical Experiments" }, { value: "15+", label: "Faculty" }, { value: "100%", label: "Lab Coverage" }, { value: "5+", label: "Research Areas" }],
    facilities: ["Physiology Lab", "Haematology Section", "Cardiovascular Lab", "Computerised Recording Systems", "Research Wing", "Demonstration Room", "e-Learning Resources", "Clinical Integration Room"],
    faqs: [
      { q: "What topics are covered in Physiology?", a: "All major organ systems — cardiovascular, respiratory, renal, endocrine, neurological, gastrointestinal, reproductive, and musculoskeletal physiology." },
      { q: "Are there practical lab sessions?", a: "Yes. Students perform 30+ experiments covering haematology, cardiovascular recordings, nerve-muscle experiments, and sensory physiology." },
      { q: "How does Physiology relate to clinical medicine?", a: "Every topic is correlated to clinical scenarios, helping students understand disease mechanisms, drug actions, and therapeutic interventions." },
    ],
  },

  biochemistry: {
    name: "Biochemistry",
    tagline: "Decoding life at the molecular level — from metabolism to disease mechanisms.",
    heroImage: "/carousel-3.png",
    splitImage: "/biochemistry_lab.png",
    splitHeading: "Chemistry of Life",
    splitText: "Our Biochemistry department provides essential knowledge of the molecular processes underlying health and disease. Well-equipped labs allow students to perform clinical biochemistry tests and understand metabolic pathways firsthand.",
    overview: "The Department of Biochemistry at Dhamma Institute of Medical Sciences covers the molecular basis of life — carbohydrate, lipid, protein, and nucleic acid metabolism — along with clinical biochemistry, enzymology, and nutrition. Students gain skills directly applicable to diagnostic medicine.",
    highlights: [
      "Fully equipped biochemistry laboratory with spectrophotometers and electrophoresis units",
      "Integration of clinical biochemistry with pathology and medicine departments",
      "Research in metabolic disorders, nutrition, and molecular biology",
      "Regular seminars and journal clubs for academic development",
      "Practical training on clinical assays — LFT, RFT, lipid profiles",
    ],
    services: [
      { title: "Carbohydrate Metabolism", desc: "Glycolysis, gluconeogenesis, glycogen metabolism, and diabetes biochemistry." },
      { title: "Protein Biochemistry", desc: "Amino acid metabolism, protein synthesis, and enzyme kinetics." },
      { title: "Lipid Metabolism", desc: "Fatty acid oxidation, lipoprotein profiles, and cholesterol metabolism." },
      { title: "Clinical Biochemistry", desc: "Liver function, kidney function, thyroid, and lipid panel interpretation." },
      { title: "Molecular Biology", desc: "DNA replication, transcription, translation, and genetic disorders." },
      { title: "Nutrition Science", desc: "Vitamins, minerals, and biochemical basis of nutritional deficiency diseases." },
    ],
    stats: [{ value: "25+", label: "Lab Experiments" }, { value: "12+", label: "Faculty" }, { value: "50+", label: "Clinical Assays" }, { value: "3+", label: "Research Projects" }],
    facilities: ["Biochemistry Lab", "Spectrophotometry Section", "Electrophoresis Unit", "Molecular Biology Lab", "Clinical Assay Section", "Research Area", "Seminar Room", "Digital Library Access"],
    faqs: [
      { q: "What is the clinical importance of Biochemistry?", a: "Biochemistry underpins all diagnostic testing — understanding metabolic pathways helps interpret lab reports and diagnose metabolic diseases." },
      { q: "Are there practical sessions in Biochemistry?", a: "Yes. Students perform 25+ experiments including estimation of glucose, proteins, lipids, and enzyme activities." },
      { q: "Does Dhamma Institute of Medical Sciences have a research programme in Biochemistry?", a: "Yes. Faculty are involved in research on metabolic disorders, nutritional deficiencies, and molecular diagnostic methods." },
    ],
  },

  pharmacology: {
    name: "Pharmacology",
    tagline: "Understanding drugs, mechanisms, and therapeutic outcomes at the molecular level.",
    heroImage: "/pharmacology_hero.png",
    splitImage: "/pharmacology_overview.png",
    splitHeading: "The Science Behind Every Treatment",
    splitText: "Pharmacology is the bridge between basic science and clinical medicine. Our department trains students to understand how drugs work, interact, and are applied safely in clinical practice through modern lab-based and simulation learning.",
    overview: "The Department of Pharmacology at Dhamma Institute of Medical Sciences provides comprehensive training in drug mechanisms, pharmacokinetics, pharmacodynamics, and clinical pharmacology. With well-equipped labs and integrated clinical teaching, students develop the knowledge needed for rational prescribing.",
    highlights: [
      "Pharmacology lab with animal and experimental models for drug testing",
      "Clinical pharmacology integration with all major clinical departments",
      "Drug interaction databases and prescription audit workshops",
      "Regular seminars on new drug approvals and adverse drug reactions",
      "Computerised data acquisition for dose-response studies",
    ],
    services: [
      { title: "General Pharmacology", desc: "Mechanisms of drug action, pharmacokinetics, and pharmacodynamics." },
      { title: "Autonomic Pharmacology", desc: "Drugs acting on sympathetic and parasympathetic nervous systems." },
      { title: "Cardiovascular Drugs", desc: "Antihypertensives, antiarrhythmics, and cardiac glycosides." },
      { title: "Antimicrobial Therapy", desc: "Antibiotics, antivirals, antifungals — spectra, resistance, and dosing." },
      { title: "CNS Pharmacology", desc: "Analgesics, anaesthetics, antidepressants, and antipsychotics." },
      { title: "Clinical Pharmacology", desc: "Rational drug use, adverse effects, drug interactions, and pharmacovigilance." },
    ],
    stats: [{ value: "200+", label: "Drug Profiles" }, { value: "15+", label: "Faculty" }, { value: "30+", label: "Lab Sessions" }, { value: "5+", label: "Research Areas" }],
    facilities: ["Pharmacology Lab", "Animal Experiment Facility", "Computerised Physiograph", "Drug Information Centre", "Clinical Pharmacology Unit", "Adverse Drug Reaction Cell", "Research Laboratory", "Seminar Hall"],
    faqs: [
      { q: "Why is Pharmacology important for MBBS students?", a: "It forms the scientific basis for all clinical prescriptions. Without understanding drug mechanisms, rational and safe prescribing is not possible." },
      { q: "What experiments are performed in the Pharmacology lab?", a: "Experiments include dose-response curves, isolated organ preparations, and computerised physiograph recordings demonstrating drug effects." },
      { q: "Is clinical pharmacology integrated into other subjects?", a: "Yes. We actively collaborate with Medicine, Surgery, Paediatrics, and Gynaecology departments to contextualise pharmacological principles clinically." },
    ],
  },

  pathology: {
    name: "Pathology",
    tagline: "Revealing the basis of disease through precise laboratory science and diagnostic expertise.",
    heroImage: "/pathology_hero.png",
    splitImage: "/pathology_overview.png",
    splitHeading: "The Language of Disease",
    splitText: "Pathology is the cornerstone of diagnosis. Our department combines histopathology, cytology, haematology, and clinical biochemistry to deliver accurate diagnostic information that guides clinical decision-making.",
    overview: "The Department of Pathology at Dhamma Institute of Medical Sciences provides comprehensive diagnostic services and academic training in general pathology, systemic pathology, haematology, microbiology, and clinical biochemistry. A fully equipped pathology laboratory ensures hands-on experience.",
    highlights: [
      "Fully operational diagnostic lab with histopathology and cytology",
      "Haematology section with automated cell counters",
      "Clinical pathology services including fluid analysis and bone marrow",
      "Integration with medicine, surgery, and oncology for multidisciplinary case review",
      "Regular grossing sessions and biopsy demonstrations",
    ],
    services: [
      { title: "Histopathology", desc: "Tissue biopsy processing, staining, and microscopic interpretation." },
      { title: "Cytopathology", desc: "FNAC, sputum cytology, cervical smears, and body fluids." },
      { title: "Haematology", desc: "Complete blood counts, peripheral smear, and coagulation studies." },
      { title: "Clinical Pathology", desc: "Urinalysis, fluid analysis, and bone marrow examination." },
      { title: "General Pathology", desc: "Cell injury, inflammation, neoplasia, and immunopathology." },
      { title: "Autopsy & Forensic Pathology", desc: "Post-mortem examination and medicolegal correlation." },
    ],
    stats: [{ value: "1000+", label: "Monthly Reports" }, { value: "20+", label: "Faculty & Lab Staff" }, { value: "48h", label: "Report Turnaround" }, { value: "100%", label: "Diagnostic Accuracy Focus" }],
    facilities: ["Histopathology Lab", "Cytology Section", "Haematology Section", "Automated Analysers", "Grossing Room", "Museum of Specimens", "Frozen Section Facility", "Research & Teaching Lab"],
    faqs: [
      { q: "What diagnostic services does Pathology offer?", a: "Full spectrum including histopathology, cytopathology (FNAC), haematology, clinical pathology, and special staining." },
      { q: "How long does a biopsy report take?", a: "Routine reports are available within 48—72 hours. Urgent and intraoperative frozen sections are provided within 30 minutes." },
      { q: "Does the department train MBBS students?", a: "Yes. An extensive practical curriculum covering specimen grossing, slide interpretation, and clinical correlation is integral to the MBBS programme." },
    ],
  },

  microbiology: {
    name: "Microbiology",
    tagline: "Combating infection through science — from bacteria to viruses to antimicrobial resistance.",
    heroImage: "/biochemistry_diagnostics.png",
    splitImage: "/carousel-4.png",
    splitHeading: "Defending Against Infection",
    splitText: "Our Microbiology department provides rigorous training in the identification and management of infectious agents. From culture and sensitivity to serology and molecular diagnostics, we prepare clinicians to address infections effectively.",
    overview: "The Department of Microbiology at Dhamma Institute of Medical Sciences is equipped for culture, identification, and sensitivity testing of bacterial, fungal, and parasitic pathogens. Serology, virology, and mycobacteriology services support clinical management of infectious diseases across all departments.",
    highlights: [
      "Biosafety Level 2 compliant microbiology laboratory",
      "Culture & sensitivity testing for bacterial and fungal infections",
      "TB diagnostics including Ziehl-Neelsen smear and CBNAAT/GeneXpert",
      "Serology for viral infections — HIV, HBV, HCV, dengue, malaria",
      "Antimicrobial resistance surveillance programme",
    ],
    services: [
      { title: "Bacteriology", desc: "Culture, identification, and antibiotic sensitivity testing of bacterial pathogens." },
      { title: "Mycology", desc: "Fungal culture, KOH mount, and identification of fungal infections." },
      { title: "Virology & Serology", desc: "ELISA, RPR, Widal, dengue, and viral hepatitis serology." },
      { title: "Mycobacteriology (TB)", desc: "AFB smear, culture on LJ media, and molecular TB diagnostics." },
      { title: "Parasitology", desc: "Stool microscopy, malaria smear, and Kala-azar serology." },
      { title: "Infection Control", desc: "Hospital infection surveillance, antibiogram reporting, and outbreak investigation." },
    ],
    stats: [{ value: "500+", label: "Monthly Cultures" }, { value: "15+", label: "Faculty & Lab Staff" }, { value: "24/7", label: "Emergency Testing" }, { value: "BSL-2", label: "Lab Compliance" }],
    facilities: ["Bacteriology Lab", "Mycology Section", "Serology Lab", "TB Diagnostics (CBNAAT)", "Blood Culture System", "Biosafety Cabinet", "Anaerobic Culture Facility", "Research & AMR Cell"],
    faqs: [
      { q: "What infections can the Microbiology lab diagnose?", a: "Bacterial (including TB), fungal, viral, and parasitic infections through culture, serology, and molecular methods." },
      { q: "Is GeneXpert/CBNAAT available for TB diagnosis?", a: "Yes. We have molecular TB diagnostics for rapid and sensitive detection of Mycobacterium tuberculosis and rifampicin resistance." },
      { q: "How does the department help with antimicrobial resistance?", a: "We publish regular antibiograms and participate in hospital infection control committees to guide empirical antibiotic therapy." },
    ],
  },

  "forensic-medicine": {
    name: "Forensic Medicine & Toxicology",
    tagline: "Bridging medicine and law through scientific investigation and medicolegal expertise.",
    heroImage: "/carousel-5.png",
    splitImage: "/carousel-1.png",
    splitHeading: "Where Medicine Meets Justice",
    splitText: "Forensic Medicine and Toxicology equips medical professionals with the skills to handle medicolegal cases, prepare evidence, conduct post-mortem examinations, and provide expert testimony in legal proceedings.",
    overview: "The Department of Forensic Medicine & Toxicology at Dhamma Institute of Medical Sciences provides comprehensive training in medicolegal examination, forensic pathology, toxicology, and clinical forensic medicine. Students gain practical skills essential for handling MLC cases, injury documentation, and participation in legal processes.",
    highlights: [
      "Autopsy hall with full post-mortem facilities",
      "Toxicology laboratory for poison identification and analysis",
      "Medicolegal case (MLC) documentation training",
      "Clinical forensic medicine and sexual assault examination protocols",
      "Court witness preparation and medicolegal report writing",
    ],
    services: [
      { title: "Forensic Pathology", desc: "Post-mortem examinations, cause of death determination, and autopsy reports." },
      { title: "Medicolegal Cases (MLC)", desc: "Documentation, examination, and reporting of injuries, assaults, and accidents." },
      { title: "Clinical Toxicology", desc: "Identification and management of poisoning cases in the emergency setting." },
      { title: "Sexual Assault Examination", desc: "Protocols for collection of evidence and clinical examination in POSH and POCSO cases." },
      { title: "Identification", desc: "Age estimation, sex determination, and forensic identification methods." },
      { title: "Expert Testimony", desc: "Court deposition training and preparation of medicolegal documentation." },
    ],
    stats: [{ value: "100+", label: "MLC Cases/Year" }, { value: "10+", label: "Faculty" }, { value: "Legal", label: "Expert Witnesses" }, { value: "24/7", label: "MLC Services" }],
    facilities: ["Autopsy Hall", "Toxicology Lab", "MLC Documentation Room", "Teaching Museum", "Forensic Photography Setup", "Evidence Storage", "Seminar Room", "Court Hall (Practice)"],
    faqs: [
      { q: "What is the role of Forensic Medicine in clinical practice?", a: "Every doctor may encounter medicolegal situations. This department trains students to handle MLC documentation, injury reporting, and court appearances correctly." },
      { q: "Does the department handle post-mortem examinations?", a: "Yes. The department conducts medico-legal autopsies and provides post-mortem reports for the Patna district." },
      { q: "What toxicology services are available?", a: "Identification of common poisons in suspected poisoning cases and guidance on antidote therapy." },
    ],
  },

  "community-medicine": {
    name: "Community Medicine",
    tagline: "Promoting health at the population level through prevention, education, and policy.",
    heroImage: "/carousel-4.png",
    splitImage: "/carousel-5.png",
    splitHeading: "Health for Every Community",
    splitText: "Community Medicine extends healthcare beyond hospital walls. Our department trains students in epidemiology, public health, and primary care, enabling them to address healthcare needs of entire communities and underserved populations.",
    overview: "The Department of Community Medicine at Dhamma Institute of Medical Sciences combines epidemiology, public health, biostatistics, social and preventive medicine, and nutrition to equip future doctors with population health skills. Field postings, rural camps, and UHSC/CHC rotations provide real-world exposure.",
    highlights: [
      "Urban and rural health sub-centre field postings",
      "Epidemiology and biostatistics training with data analysis",
      "National health programme orientation and implementation",
      "Research in community health, nutrition, and maternal-child health",
      "Regular health camps and community outreach programmes",
    ],
    services: [
      { title: "Epidemiology", desc: "Disease surveillance, outbreak investigation, and epidemiological study design." },
      { title: "Biostatistics", desc: "Statistical methods for health data, study design, and research analysis." },
      { title: "Maternal & Child Health", desc: "Antenatal, postnatal, immunisation, and growth monitoring programmes." },
      { title: "Environmental Health", desc: "Water quality, sanitation, vector control, and occupational health." },
      { title: "National Health Programmes", desc: "RNTCP, NVBDCP, RCH, NHM — implementation and monitoring." },
      { title: "Health Education", desc: "BCC strategies, IEC material development, and community awareness." },
    ],
    stats: [{ value: "2", label: "Field Stations" }, { value: "10+", label: "Faculty" }, { value: "5000+", label: "Camp Beneficiaries/Year" }, { value: "100%", label: "Field Posting Coverage" }],
    facilities: ["Demonstration Room", "Epidemiology Lab", "Biostatistics Section", "Rural Health Centre", "Urban Health Sub-centre", "Nutrition Lab", "Health Education Unit", "Research & Survey Room"],
    faqs: [
      { q: "What is Social and Preventive Medicine?", a: "It covers population-level health, disease prevention, health promotion, and social determinants of health — essential for every MBBS graduate." },
      { q: "Do students get field postings?", a: "Yes. Compulsory rural and urban health sub-centre postings provide direct community health experience as part of the MBBS curriculum." },
      { q: "Is research conducted in this department?", a: "Yes. Community-based research on maternal health, nutrition, infectious diseases, and healthcare access is actively conducted." },
    ],
  },

  ent: {
    name: "Otorhinolaryngology (ENT)",
    tagline: "Expert care for ear, nose, and throat conditions — from hearing loss to complex head-neck surgery.",
    heroImage: "/hospital_opd_hero.png",
    splitImage: "/carousel-2.png",
    splitHeading: "Precision ENT Care",
    splitText: "Our ENT department offers comprehensive diagnosis and surgical management of disorders affecting the ear, nose, throat, larynx, and neck. With modern endoscopic and audiological equipment, we deliver accurate diagnosis and minimally invasive treatments.",
    overview: "The Department of ENT at Dhamma Institute of Medical Sciences provides full-spectrum care for ear diseases (hearing loss, CSOM, otitis media), nasal conditions (sinusitis, polyps, DNS), throat and laryngeal disorders, and head-neck tumours. Our team handles both emergency and elective ENT cases.",
    highlights: [
      "Endoscopic sinus surgery (FESS) and nasal endoscopy",
      "Comprehensive audiometry and hearing evaluation services",
      "Microsurgery of the ear — tympanoplasty and mastoid surgery",
      "Voice and laryngoscopy clinic for vocal cord disorders",
      "Head and neck cancer evaluation and surgical management",
    ],
    services: [
      { title: "Ear Disorders", desc: "CSOM, otitis media, hearing loss, tinnitus, and ear surgery (tympanoplasty, mastoidectomy)." },
      { title: "Nasal & Sinus", desc: "DNS, sinusitis, nasal polyps, and endoscopic sinus surgery (FESS)." },
      { title: "Throat & Larynx", desc: "Tonsillitis, adenoids, voice disorders, laryngoscopy, and tonsillectomy." },
      { title: "Audiological Services", desc: "Pure tone audiometry, impedance audiometry, BERA, and hearing aid fitting." },
      { title: "Head & Neck Surgery", desc: "Thyroid, parotid, salivary gland, and lymph node surgeries." },
      { title: "Paediatric ENT", desc: "Hearing screening, adenotonsillectomy, foreign body removal, and ear tube placement." },
    ],
    stats: [{ value: "500+", label: "ENT OPD/Month" }, { value: "50+", label: "Surgeries/Month" }, { value: "24/7", label: "ENT Emergency" }, { value: "10+", label: "Faculty & Residents" }],
    facilities: ["ENT OPD", "Endoscopy Suite", "Audiometry Unit", "Hearing Aid Centre", "Operation Theatre", "Voice Clinic", "BERA Lab", "Emergency ENT Care"],
    faqs: [
      { q: "What ENT surgeries are performed at Dhamma Institute of Medical Sciences?", a: "Tympanoplasty, FESS, septoplasty, tonsillectomy, adenoidectomy, microlaryngoscopy, and head-neck surgeries are performed regularly." },
      { q: "Is audiometry available for children?", a: "Yes. We offer paediatric audiological evaluation including BERA for infants and newborn hearing screening." },
      { q: "Can sinusitis be treated without surgery?", a: "Mild to moderate sinusitis is treated medically. Chronic or recurrent cases may require endoscopic sinus surgery (FESS)." },
    ],
  },

  ophthalmology: {
    name: "Ophthalmology",
    tagline: "Restoring and preserving sight through advanced diagnostics and precision eye care.",
    heroImage: "/hospital_ipd_hero.png",
    splitImage: "/carousel-3.png",
    splitHeading: "See the World Clearly",
    splitText: "Our Ophthalmology department offers comprehensive eye care from routine refraction to complex retinal surgery. Modern equipment ensures accurate diagnosis and effective treatment for all conditions of the eye and visual pathway.",
    overview: "The Department of Ophthalmology at Dhamma Institute of Medical Sciences provides complete eye care services including cataract surgery, glaucoma management, diabetic retinopathy care, corneal diseases, paediatric ophthalmology, and low vision aids. We serve both urban and rural patients with quality eye care.",
    highlights: [
      "Phacoemulsification cataract surgery with intraocular lens implant",
      "Glaucoma clinic with IOP monitoring and visual field analysis",
      "Diabetic retinopathy screening and laser photocoagulation",
      "Paediatric eye care — amblyopia, squint, and refractive errors",
      "Community eye camps and school vision screening programmes",
    ],
    services: [
      { title: "Cataract Surgery", desc: "Phacoemulsification with premium IOL implantation for clear, rapid recovery." },
      { title: "Glaucoma Management", desc: "IOP monitoring, visual field testing, medical and surgical glaucoma care." },
      { title: "Retinal Services", desc: "Diabetic retinopathy, macular degeneration, retinal detachment, and laser therapy." },
      { title: "Paediatric Ophthalmology", desc: "Squint surgery, amblyopia therapy, and congenital eye disorders." },
      { title: "Cornea & Refractive", desc: "Corneal ulcers, keratoconus management, and refractive error correction." },
      { title: "Oculoplasty", desc: "Lid surgeries, lacrimal system procedures, and orbital disorders." },
    ],
    stats: [{ value: "300+", label: "OPD/Month" }, { value: "40+", label: "Surgeries/Month" }, { value: "5+", label: "Sub-specialities" }, { value: "Free", label: "Camp Eye Surgeries" }],
    facilities: ["Eye OPD", "Operation Theatre", "Slit Lamp Units", "OCT Machine", "Visual Field Analyser", "Laser Photocoagulation Unit", "Phacoemulsification System", "Low Vision Aid Clinic"],
    faqs: [
      { q: "Is cataract surgery safe at Dhamma Institute of Medical Sciences?", a: "Yes. We perform phacoemulsification with modern intraocular lenses. The procedure is safe, quick, and requires minimal recovery time." },
      { q: "Are diabetic eye complications managed here?", a: "Yes. We offer complete diabetic eye screening and management including laser photocoagulation and intravitreal injections." },
      { q: "Does Dhamma Institute of Medical Sciences conduct eye camps?", a: "Yes. Regular free eye camps are organised in rural areas with cataract surgeries, spectacle distribution, and eye health education." },
    ],
  },

  orthopaedics: {
    name: "Orthopaedics",
    tagline: "Restoring mobility and function through expert bone, joint, and musculoskeletal care.",
    heroImage: "/hospital_main_hero.png",
    splitImage: "/carousel-1.png",
    splitHeading: "Back to Motion",
    splitText: "Our Orthopaedics department specialises in the complete spectrum of bone and joint conditions — from acute trauma to complex reconstructive surgery. We restore function, reduce pain, and enable patients to return to normal life.",
    overview: "The Department of Orthopaedics at Dhamma Institute of Medical Sciences handles trauma, fractures, joint replacements, sports injuries, spine surgery, and paediatric orthopaedics. A fully equipped operation theatre with C-arm imaging, implant storage, and dedicated physiotherapy enables comprehensive orthopaedic care.",
    highlights: [
      "Trauma care with emergency fracture fixation and polytrauma management",
      "Joint replacement surgery — hip and knee arthroplasty",
      "Spine surgery for disc prolapse, spondylolisthesis, and spinal stenosis",
      "Arthroscopic surgery for shoulder, knee, and ankle joint disorders",
      "Paediatric orthopaedics including clubfoot, DDH, and limb deformities",
    ],
    services: [
      { title: "Trauma & Fracture Management", desc: "Emergency fracture fixation — nailing, plating, and external fixation." },
      { title: "Joint Replacement", desc: "Total hip and total knee arthroplasty with modern prosthetic systems." },
      { title: "Spine Surgery", desc: "Discectomy, laminectomy, fusion, and minimally invasive spine procedures." },
      { title: "Arthroscopy", desc: "Keyhole surgery for ACL reconstruction, meniscal repair, and shoulder stabilisation." },
      { title: "Paediatric Orthopaedics", desc: "Clubfoot correction, hip dysplasia, and limb deformity management." },
      { title: "Physiotherapy & Rehab", desc: "Post-operative rehabilitation, physiotherapy, and orthotics support." },
    ],
    stats: [{ value: "100+", label: "Surgeries/Month" }, { value: "24/7", label: "Trauma Emergency" }, { value: "15+", label: "Faculty & Residents" }, { value: "C-Arm", label: "Intraoperative Imaging" }],
    facilities: ["Ortho OT with C-Arm", "Trauma ICU", "Implant Store", "Cast & Splint Room", "Physiotherapy Department", "Spine Surgery Suite", "Arthroscopy Setup", "Fracture Clinic"],
    faqs: [
      { q: "Does Dhamma Institute of Medical Sciences handle emergency fractures?", a: "Yes. Our trauma team is available 24/7 for emergency fracture fixation including road traffic accidents and polytrauma cases." },
      { q: "Are joint replacement surgeries performed?", a: "Yes. We perform total knee and hip replacements using high-quality prostheses with full physiotherapy support." },
      { q: "What is the recovery time after knee replacement?", a: "Patients typically begin walking with support within 24—48 hours and achieve full function within 6—12 weeks." },
    ],
  },

  "general-medicine": {
    name: "General Medicine",
    tagline: "Comprehensive internal medicine — diagnosing and treating diseases across all organ systems.",
    heroImage: "/hospital_opd_hero.png",
    splitImage: "/carousel-2.png",
    splitHeading: "The Heart of Clinical Care",
    splitText: "General Medicine is the largest clinical department, managing the broadest spectrum of diseases. Our team of internists provides holistic, evidence-based care for acute and chronic medical conditions with a focus on patient outcomes.",
    overview: "The Department of General Medicine at Dhamma Institute of Medical Sciences manages all common and complex medical conditions including cardiovascular diseases, respiratory disorders, neurological conditions, endocrine diseases, infections, and critical care. As the backbone of clinical services, it provides round-the-clock inpatient and outpatient care.",
    highlights: [
      "ICU and HDU for medical emergencies and critical care",
      "Dedicated clinics for diabetes, hypertension, and asthma management",
      "Neurology referral clinic with EEG and nerve conduction studies",
      "Tropical medicine — dengue, malaria, typhoid, leptospirosis management",
      "Comprehensive management of multi-system diseases and geriatric care",
    ],
    services: [
      { title: "Cardiology", desc: "ECG, echocardiography, hypertension, IHD, and cardiac emergencies." },
      { title: "Respiratory Medicine", desc: "Asthma, COPD, pneumonia, pleural diseases, and respiratory failure." },
      { title: "Endocrinology", desc: "Diabetes mellitus, thyroid disorders, adrenal, and pituitary diseases." },
      { title: "Neurology", desc: "Stroke, epilepsy, headache, neuropathy, and movement disorders." },
      { title: "Infectious Diseases", desc: "Tropical infections, fever workup, sepsis, and antimicrobial management." },
      { title: "Nephrology & Gastroenterology", desc: "CKD, liver diseases, GI bleeding, and inflammatory bowel disease." },
    ],
    stats: [{ value: "500+", label: "OPD Daily" }, { value: "100+", label: "Beds" }, { value: "24/7", label: "Emergency Cover" }, { value: "20+", label: "Faculty & Residents" }],
    facilities: ["General Medicine Wards", "ICU & HDU", "Procedure Room", "ECG & Echocardiography", "Diabetes Clinic", "Hypertension Clinic", "Neurology Clinic", "Emergency Medicine"],
    faqs: [
      { q: "What types of cases are managed in General Medicine?", a: "All non-surgical acute and chronic medical conditions — cardiovascular, respiratory, neurological, endocrine, gastrointestinal, renal, and infectious diseases." },
      { q: "Is ICU care available?", a: "Yes. Our medical ICU manages critical conditions including sepsis, respiratory failure, cardiac events, and multi-organ dysfunction." },
      { q: "Does Dhamma Institute of Medical Sciences have a diabetes management programme?", a: "Yes. We have a dedicated diabetes clinic with HbA1c testing, dietitian support, and complication screening." },
    ],
  },

  "general-surgery": {
    name: "General Surgery",
    tagline: "Expert surgical care — from emergency operations to complex elective procedures.",
    heroImage: "/carousel-1.png",
    splitImage: "/hospital_ipd_hero.png",
    splitHeading: "Surgical Excellence at Every Level",
    splitText: "Our General Surgery department delivers evidence-based, patient-centric surgical care for a wide range of conditions. With experienced surgeons and a modern operation theatre, we handle both emergency and elective cases with precision and safety.",
    overview: "The Department of General Surgery at Dhamma Institute of Medical Sciences provides comprehensive surgical services covering abdominal, breast, thyroid, hernia, anorectal, vascular, and trauma surgery. A modern operation theatre with laparoscopic equipment supports both open and minimally invasive surgical procedures.",
    highlights: [
      "Laparoscopic surgery — cholecystectomy, appendicectomy, and hernia repair",
      "Breast surgery — wide local excision, mastectomy, and oncoplasty",
      "Thyroid and parathyroid surgery",
      "Colorectal surgery — haemorrhoids, fissure, fistula, and bowel resections",
      "Vascular surgery — varicose veins and peripheral vascular disease",
    ],
    services: [
      { title: "Emergency Surgery", desc: "Acute abdomen, perforations, obstructions, trauma, and appendicitis." },
      { title: "Laparoscopic Surgery", desc: "Minimally invasive cholecystectomy, hernia repair, and diagnostic laparoscopy." },
      { title: "Breast Surgery", desc: "Fibroadenoma, breast cancer surgery, and reconstruction." },
      { title: "Thyroid & Endocrine", desc: "Total/partial thyroidectomy, parathyroidectomy, and adrenalectomy." },
      { title: "Anorectal Surgery", desc: "Haemorrhoidectomy, fistula repair, fissurectomy, and pilonidal sinus." },
      { title: "Hernia Repair", desc: "Open and laparoscopic repair — inguinal, femoral, umbilical, and incisional." },
    ],
    stats: [{ value: "150+", label: "Surgeries/Month" }, { value: "24/7", label: "Emergency Surgery" }, { value: "15+", label: "Faculty & Residents" }, { value: "Lap+Open", label: "Surgical Techniques" }],
    facilities: ["Modular OT Suite", "Laparoscopic Tower", "ICU & Recovery Ward", "Pre-op Assessment Clinic", "Surgical Oncology Suite", "Endoscopy Suite", "Wound Care Clinic", "Day Surgery Unit"],
    faqs: [
      { q: "Is laparoscopic surgery available at Dhamma Institute of Medical Sciences?", a: "Yes. We perform laparoscopic cholecystectomy, appendicectomy, hernia repair, and other minimally invasive procedures with faster recovery." },
      { q: "Does the department handle emergency surgical cases?", a: "Yes. Our emergency surgical team is available 24/7 for acute abdomen, perforations, trauma, and other surgical emergencies." },
      { q: "What is the typical hospital stay after laparoscopic surgery?", a: "Most laparoscopic procedures require only 1—2 days of hospitalisation with return to normal activities within a week." },
    ],
  },

  paediatrics: {
    name: "Paediatrics",
    tagline: "Caring for the health of children — from newborn to adolescence — with compassion and expertise.",
    heroImage: "/carousel-3.png",
    splitImage: "/carousel-5.png",
    splitHeading: "Every Child Deserves the Best Care",
    splitText: "Our Paediatrics department provides holistic child health services from the NICU to adolescent medicine. We combine clinical expertise with a child-friendly environment to ensure the best possible outcomes for our youngest patients.",
    overview: "The Department of Paediatrics at Dhamma Institute of Medical Sciences provides comprehensive healthcare for neonates, infants, children, and adolescents. NICU, PICU, and dedicated paediatric wards ensure specialised care at every stage of childhood with round-the-clock specialist coverage.",
    highlights: [
      "Neonatal Intensive Care Unit (NICU) for preterm and sick neonates",
      "Paediatric Intensive Care Unit (PICU) for critically ill children",
      "Comprehensive immunisation clinic and growth monitoring",
      "Paediatric nutrition and developmental assessment clinic",
      "Management of neonatal jaundice, sepsis, and respiratory distress",
    ],
    services: [
      { title: "Neonatal Care", desc: "NICU care for preterm, low birth weight, and sick neonates." },
      { title: "Paediatric ICU", desc: "Critical care for children with severe infections, respiratory failure, and emergencies." },
      { title: "Immunisation Clinic", desc: "National immunisation schedule and special vaccines for children." },
      { title: "Nutrition & Growth", desc: "Nutritional assessment, management of malnutrition, and growth monitoring." },
      { title: "Developmental Paediatrics", desc: "Developmental delay, autism spectrum, and neurodevelopmental assessments." },
      { title: "Paediatric Emergencies", desc: "Febrile seizures, dehydration, acute respiratory distress, and trauma management." },
    ],
    stats: [{ value: "20", label: "NICU Beds" }, { value: "10", label: "PICU Beds" }, { value: "24/7", label: "Specialist Cover" }, { value: "100%", label: "Immunisation Programme" }],
    facilities: ["NICU", "PICU", "Paediatric Wards", "Immunisation Room", "Growth Monitoring Clinic", "Neonatal Resuscitation", "Phototherapy Units", "Paediatric Emergency"],
    faqs: [
      { q: "What is the capacity of Dhamma Institute of Medical Sciences's NICU?", a: "Our NICU has 20 beds equipped for ventilatory support, phototherapy, parenteral nutrition, and advanced neonatal monitoring." },
      { q: "Does Dhamma Institute of Medical Sciences follow the national immunisation schedule?", a: "Yes. We follow the Universal Immunisation Programme (UIP) and also offer additional vaccines as recommended by the IAP." },
      { q: "Are paediatric emergencies handled 24/7?", a: "Yes. Our paediatric team including NICU and PICU specialists are available round the clock for all emergencies." },
    ],
  },

  "obstetrics-gynecology": {
    name: "Obstetrics & Gynecology",
    tagline: "Comprehensive care for women — through pregnancy, childbirth, and every phase of reproductive health.",
    heroImage: "/carousel-2.png",
    splitImage: "/carousel-4.png",
    splitHeading: "Celebrating Every Birth, Supporting Every Woman",
    splitText: "Our Obstetrics and Gynecology department is committed to ensuring safe motherhood and comprehensive women's health care. From high-risk pregnancy management to minimally invasive gynaecological surgery, we provide expert, compassionate care.",
    overview: "The Department of Obstetrics & Gynecology at Dhamma Institute of Medical Sciences delivers comprehensive maternal and women's healthcare. Our services encompass high-risk pregnancy, labour and delivery, LSCS, laparoscopic gynaecological surgery, infertility evaluation, and menstrual disorder management.",
    highlights: [
      "High-risk pregnancy management and antenatal care",
      "Labour ward with continuous foetal monitoring",
      "Laparoscopic and hysteroscopic gynaecological procedures",
      "Infertility evaluation and basic ART counselling",
      "Colposcopy and cervical cancer screening programme",
    ],
    services: [
      { title: "Antenatal Care", desc: "Regular ANC, high-risk pregnancy monitoring, and foetal wellbeing assessment." },
      { title: "Labour & Delivery", desc: "Normal vaginal delivery, instrumental delivery, and emergency LSCS." },
      { title: "Gynaecological Surgery", desc: "Laparoscopy, hysteroscopy, myomectomy, hysterectomy, and ovarian cyst surgery." },
      { title: "Menstrual Disorders", desc: "PCOD, fibroids, endometriosis, and abnormal uterine bleeding management." },
      { title: "Infertility Evaluation", desc: "Couple evaluation, ovulation induction, and referral for ART." },
      { title: "Cancer Screening", desc: "Cervical smear, colposcopy, and early detection of gynaecological cancers." },
    ],
    stats: [{ value: "100+", label: "Deliveries/Month" }, { value: "24/7", label: "Labour Ward Cover" }, { value: "20+", label: "Gynaec Surgeries/Month" }, { value: "15+", label: "Faculty & Residents" }],
    facilities: ["Labour Room Suite", "LSCS OT", "Antenatal Clinic", "Gynaecology OPD", "Laparoscopy Suite", "Colposcopy Clinic", "Foetal Monitoring Unit", "Postnatal Wards"],
    faqs: [
      { q: "Does Dhamma Institute of Medical Sciences handle high-risk pregnancies?", a: "Yes. We have a dedicated high-risk obstetrics clinic and facility for management of pre-eclampsia, GDM, multiple pregnancies, and foetal complications." },
      { q: "Is laparoscopic gynaecological surgery available?", a: "Yes. Laparoscopic procedures including ovarian cystectomy, myomectomy, ectopic surgery, and diagnostic laparoscopy are performed regularly." },
      { q: "What cancer screening services are available?", a: "Cervical cancer screening with PAP smear and colposcopy is available. VIA/VILI screening is also offered for early detection." },
    ],
  },

  psychiatry: {
    name: "Psychiatry",
    tagline: "Supporting mental health through evidence-based care, compassion, and destigmatisation.",
    heroImage: "/carousel-5.png",
    splitImage: "/carousel-1.png",
    splitHeading: "Mental Health is Health",
    splitText: "Our Psychiatry department provides a full spectrum of mental health services in a supportive, non-judgmental environment. From assessment and therapy to pharmacological management, we are committed to mental wellbeing for every patient.",
    overview: "The Department of Psychiatry at Dhamma Institute of Medical Sciences provides comprehensive mental health services including assessment, diagnosis, and management of psychiatric disorders. Services cover depression, anxiety, schizophrenia, substance abuse, psychosomatic disorders, and liaison psychiatry across all clinical departments.",
    highlights: [
      "Outpatient and inpatient psychiatric services with dedicated wards",
      "Psychotherapy including CBT and supportive therapy",
      "Substance abuse and de-addiction programme",
      "Child and adolescent mental health services",
      "Liaison psychiatry for medically ill patients across departments",
    ],
    services: [
      { title: "Depression & Anxiety", desc: "Evidence-based pharmacological and psychotherapeutic management." },
      { title: "Schizophrenia & Psychosis", desc: "Acute management, maintenance therapy, and community rehabilitation." },
      { title: "Substance Abuse", desc: "De-addiction programme for alcohol, opioids, and other substance use disorders." },
      { title: "Child Psychiatry", desc: "ADHD, autism spectrum disorder, conduct disorder, and school refusal." },
      { title: "Psychotherapy", desc: "Cognitive behavioural therapy (CBT), supportive therapy, and relaxation training." },
      { title: "Liaison Psychiatry", desc: "Mental health consultation for medically ill patients in other departments." },
    ],
    stats: [{ value: "200+", label: "OPD/Month" }, { value: "10+", label: "Beds" }, { value: "10+", label: "Faculty & Staff" }, { value: "24/7", label: "Psychiatric Emergency" }],
    facilities: ["Outpatient Clinic", "Psychiatric Ward", "Psychotherapy Rooms", "De-addiction Centre", "ECT Suite", "Group Therapy Room", "Child Psychiatry Clinic", "Liaison Psychiatry Services"],
    faqs: [
      { q: "Is psychiatric consultation confidential?", a: "Absolutely. All consultations, records, and treatment information are strictly confidential and governed by medical ethics and Indian law." },
      { q: "Does Dhamma Institute of Medical Sciences offer de-addiction services?", a: "Yes. We have a structured de-addiction and rehabilitation programme for alcohol, opioid, and other substance use disorders." },
      { q: "Are psychotherapy services available?", a: "Yes. We offer CBT, supportive psychotherapy, and relaxation therapy. Our trained therapists work alongside psychiatrists for holistic care." },
    ],
  },

  radiology: {
    name: "Radiology",
    tagline: "Precision imaging for accurate diagnosis — supporting clinical decisions across every department.",
    heroImage: "/hospital_ipd_hero.png",
    splitImage: "/biochemistry_diagnostics.png",
    splitHeading: "Where Diagnosis Begins",
    splitText: "Modern radiology is the backbone of clinical medicine. Our Radiology department provides a full suite of imaging services — from plain X-rays to advanced MRI and CT scans — enabling fast and accurate diagnosis to guide treatment.",
    overview: "The Department of Radiology at Dhamma Institute of Medical Sciences provides comprehensive diagnostic imaging and interventional radiology services including X-ray, ultrasonography, CT scan, MRI, and fluoroscopy. Detailed reporting by experienced radiologists supports all clinical departments.",
    highlights: [
      "Multidetector CT scanner with thin-slice imaging",
      "1.5 Tesla MRI for neurological, musculoskeletal, and abdominal imaging",
      "Colour Doppler ultrasonography for vascular and obstetric imaging",
      "Digital X-ray with PACS for instant image access",
      "Interventional radiology — USG-guided FNAC, biopsies, and drainages",
    ],
    services: [
      { title: "X-Ray", desc: "Digital radiography for chest, bone, abdomen, and all routine indications." },
      { title: "Ultrasonography", desc: "Abdominal, pelvic, obstetric, thyroid, and musculoskeletal ultrasound." },
      { title: "CT Scan", desc: "Head, chest, abdomen, trauma, and angiography CT protocols." },
      { title: "MRI", desc: "Brain, spine, abdomen, joints, and cardiac MRI imaging." },
      { title: "Colour Doppler", desc: "Vascular, renal, portal, and foetal Doppler studies." },
      { title: "Interventional Radiology", desc: "USG-guided FNAC, biopsies, abscess drainage, and tumour localisation." },
    ],
    stats: [{ value: "200+", label: "Scans/Day" }, { value: "24/7", label: "Emergency Imaging" }, { value: "1.5T", label: "MRI Strength" }, { value: "<4h", label: "Report Turnaround" }],
    facilities: ["Digital X-Ray", "CT Scanner", "MRI Machine", "Ultrasound Suites", "Mammography Unit", "Fluoroscopy Suite", "PACS System", "Interventional Suite"],
    faqs: [
      { q: "Is MRI available at Dhamma Institute of Medical Sciences?", a: "Yes. We have a 1.5 Tesla MRI providing high-resolution imaging for brain, spine, joints, and abdominal organs." },
      { q: "How soon are reports available?", a: "Routine reports are available within 4—6 hours. Emergency reports (trauma, stroke, acute abdomen) are prioritised immediately." },
      { q: "Is radiation safe in CT scans?", a: "CT scans use low doses of ionising radiation and are considered safe when clinically indicated. Our radiologists optimise protocols to minimise dose." },
    ],
  },

  dermatology: {
    name: "Dermatology, Venereology & Leprosy",
    tagline: "Expert skin care — from common dermatoses to complex immunological and infectious diseases.",
    heroImage: "/career_hero.png",
    splitImage: "/carousel-3.png",
    splitHeading: "Healthy Skin, Confident Life",
    splitText: "Our Dermatology department provides specialised care for all skin, hair, and nail conditions. From acne and eczema to psoriasis and sexually transmitted infections, we deliver evidence-based dermatological care with modern treatment modalities.",
    overview: "The Department of Dermatology, Venereology & Leprosy at Dhamma Institute of Medical Sciences provides comprehensive care for skin diseases including common inflammatory dermatoses, infectious skin conditions, STIs, leprosy, pigmentation disorders, and procedural dermatology.",
    highlights: [
      "Dermatoscopy for pigmented lesion analysis and skin cancer screening",
      "Phototherapy (NBUVB) for psoriasis and vitiligo",
      "Sexually transmitted infection (STI) and HIV-related dermatology clinic",
      "Leprosy diagnosis, treatment, and reaction management",
      "Minor surgical procedures — punch biopsy, cryotherapy, and dermabrasion",
    ],
    services: [
      { title: "Common Skin Diseases", desc: "Eczema, dermatitis, urticaria, psoriasis, and inflammatory skin conditions." },
      { title: "Infections & Infestations", desc: "Fungal infections, bacterial skin diseases, viral warts, and scabies." },
      { title: "Vitiligo & Pigmentation", desc: "Vitiligo NBUVB therapy, melasma management, and pigmentation disorders." },
      { title: "STI & HIV Skin", desc: "Diagnosis and management of sexually transmitted infections and HIV dermatology." },
      { title: "Leprosy", desc: "Diagnosis, treatment (MDT), and management of reactions and deformity prevention." },
      { title: "Procedural Dermatology", desc: "Chemical peels, cryotherapy, intralesional injections, and biopsies." },
    ],
    stats: [{ value: "300+", label: "OPD/Month" }, { value: "10+", label: "Faculty" }, { value: "NBUVB", label: "Phototherapy Available" }, { value: "STI", label: "Specialised Clinic" }],
    facilities: ["Dermatology OPD", "Dermatoscopy Unit", "NBUVB Phototherapy", "STI Clinic", "Leprosy Clinic", "Procedure Room", "Patch Test Section", "Laser Suite"],
    faqs: [
      { q: "Is phototherapy available for vitiligo and psoriasis?", a: "Yes. Narrowband UVB (NBUVB) phototherapy is available and is an effective treatment for vitiligo, psoriasis, and other chronic skin diseases." },
      { q: "Are STI and HIV skin manifestations managed here?", a: "Yes. We have a dedicated STI clinic following national protocols for diagnosis, treatment, contact tracing, and counselling." },
      { q: "Does Dhamma Institute of Medical Sciences treat leprosy?", a: "Yes. We provide complete leprosy care including diagnosis, multi-drug therapy (MDT), reaction management, and disability prevention." },
    ],
  },

  dentistry: {
    name: "Dentistry",
    tagline: "Healthy smiles, confident lives — comprehensive oral and dental healthcare at Dhamma Institute of Medical Sciences.",
    heroImage: "/carousel-4.png",
    splitImage: "/carousel-2.png",
    splitHeading: "Your Smile is Our Priority",
    splitText: "Our Dentistry department provides a full range of dental and oral health services. From routine fillings to oral surgery and cosmetic dentistry, our qualified dentists ensure every patient leaves with a healthier, brighter smile.",
    overview: "The Department of Dentistry at Dhamma Institute of Medical Sciences provides comprehensive oral health services including dental caries management, periodontal care, oral surgery, prosthetics, orthodontics, and oral pathology. A fully equipped dental clinic ensures quality care for all dental conditions.",
    highlights: [
      "Digital OPG X-ray for full oral and maxillofacial assessment",
      "Oral surgery including wisdom tooth extraction and implants",
      "Root canal treatment (RCT) with modern endodontic instruments",
      "Periodontal care — scaling, root planing, and flap surgery",
      "Fixed and removable prosthodontics and crowns",
    ],
    services: [
      { title: "Restorative Dentistry", desc: "Tooth fillings, bonding, and composite restorations for dental caries." },
      { title: "Root Canal Treatment", desc: "Endodontic therapy for infected or damaged teeth to preserve natural dentition." },
      { title: "Oral Surgery", desc: "Extractions, wisdom tooth surgery, cyst removal, and implant placement." },
      { title: "Periodontics", desc: "Scaling, root planing, gingivitis, periodontitis, and gum surgery." },
      { title: "Prosthodontics", desc: "Crowns, bridges, complete and partial dentures, and dental implants." },
      { title: "Orthodontics", desc: "Braces, aligners, and correction of malocclusion and dental crowding." },
    ],
    stats: [{ value: "150+", label: "Patients/Month" }, { value: "10+", label: "Dental Chairs" }, { value: "Digital", label: "OPG X-Ray" }, { value: "All", label: "Specialities" }],
    facilities: ["Modern Dental Chairs", "Digital OPG X-Ray", "Dental Surgery Suite", "Sterilisation Unit", "RCT Suite", "Orthodontic Clinic", "Dental Lab", "Oral Cancer Screening"],
    faqs: [
      { q: "Is root canal treatment painful?", a: "Modern RCT with local anaesthesia is virtually painless. Most patients experience minimal discomfort during and after the procedure." },
      { q: "Are dental implants available at Dhamma Institute of Medical Sciences?", a: "Yes. We offer dental implant placement and restoration as a permanent solution for missing teeth." },
      { q: "Does Dhamma Institute of Medical Sciences provide orthodontic treatment?", a: "Yes. We offer fixed braces and aligners for correction of crowded, spaced, or misaligned teeth." },
    ],
  },

  anaesthesiology: {
    name: "Anaesthesiology",
    tagline: "Ensuring safe, painless surgery — precision anaesthesia and critical care at every step.",
    heroImage: "/carousel-5.png",
    splitImage: "/carousel-3.png",
    splitHeading: "Your Safety is Our Priority",
    splitText: "Our Anaesthesiology department ensures the safety and comfort of every patient undergoing surgery or procedure. From pre-operative assessment to post-operative care, our anaesthetists are present at every critical step.",
    overview: "The Department of Anaesthesiology at Dhamma Institute of Medical Sciences is responsible for safe anaesthesia delivery across all surgical specialities, critical care management in the ICU, pain clinic services, and emergency resuscitation. Our team of experienced anaesthesiologists ensures optimal patient safety.",
    highlights: [
      "General, regional, and neuraxial anaesthesia for all surgical specialities",
      "Anaesthesia for high-risk patients — cardiac, obstetric, and paediatric",
      "Critical care management in surgical ICU",
      "Pain management clinic for acute and chronic pain",
      "Emergency resuscitation and advanced airway management",
    ],
    services: [
      { title: "General Anaesthesia", desc: "Safe induction and maintenance of GA for all surgical procedures." },
      { title: "Regional Anaesthesia", desc: "Spinal, epidural, and nerve blocks for surgeries and pain management." },
      { title: "Paediatric Anaesthesia", desc: "Specialised techniques for neonates, infants, and children." },
      { title: "Obstetric Anaesthesia", desc: "Epidural analgesia for labour and spinal/GA for LSCS." },
      { title: "Critical Care", desc: "Mechanical ventilation, haemodynamic monitoring, and ICU management." },
      { title: "Pain Clinic", desc: "Management of acute post-operative pain and chronic pain syndromes." },
    ],
    stats: [{ value: "100+", label: "Cases/Month" }, { value: "24/7", label: "Emergency Cover" }, { value: "All", label: "Surgical Specialities" }, { value: "ICU", label: "Critical Care" }],
    facilities: ["Anaesthesia Workstations", "ICU (Surgical)", "Post-Anaesthesia Care Unit", "Pain Clinic", "Airway Management Trolley", "Regional Anaesthesia Suite", "Emergency Cart", "Paediatric Anaesthesia Setup"],
    faqs: [
      { q: "Is anaesthesia safe for elderly patients?", a: "Yes. With proper pre-operative assessment and monitoring, anaesthesia is safe for all age groups. Our team tailors the approach to individual risk factors." },
      { q: "What is regional anaesthesia?", a: "Regional anaesthesia (spinal/epidural/nerve blocks) numbs only part of the body, avoiding general anaesthesia and allowing faster recovery." },
      { q: "Is pain management available after surgery?", a: "Yes. Our pain clinic provides multimodal analgesia protocols for post-operative pain and manages chronic pain conditions." },
    ],
  },

};

export default departments;
